#!/usr/bin/env bash
#echo _gg_check_layer:

. $(which _gg_lib)

[ -f /tmp/gg_layer.env ] && . /tmp/gg_layer.env

if [ -z "$GG_LAYER" ]; then
	echo "_gg_check_layer: GG_LAYER is not set."
	echo "_gg_check_layer: Run gglayer <layer_name> to create/select layer."
	echo _gg_check_layer: Available layers:
	list_layers
	exit 1
fi

# define working directories
_WORK_DIR=$GG_BACKUP_ROOT

# add ending slash if absent
[[ "$_WORK_DIR" != */ ]] && _WORK_DIR="$_WORK_DIR"/

_LAYER_DIR="$_WORK_DIR$GG_LAYER"
_WORK_DIR="$_LAYER_DIR/_root"
metadata_file="$_LAYER_DIR/.permissions"

if [ -d "$_WORK_DIR" ]; then
	printf "Selected layer: " && print_style "$GG_LAYER\n" "" orange
	printf "Working directory: " && print_style "$_WORK_DIR\n" "" orange
else
	echo "Working dir not found." && exit 1
fi
