#!/usr/bin/env bash

. $(which _gg_check_root)
. $(which _gg_check_layer)


help="
Usage: ggadd <path>
"

[ -z "$1" ] && echo $help && exit 0
# realpath resolves symlinks and returns the absolute path:
# realpath -q /dev/log => /var/run/log
# Handle realpath differences between Linux and BSD
if [ "$os" == "Linux" ]; then
    file_to_add="$(realpath "$1" 2>/dev/null)"
else
    file_to_add="$(realpath -q "$1" 2>/dev/null)"
fi

echo "Adding to backup: $file_to_add"

# final checks
[[ -d "$file_to_add" || -f "$file_to_add" ]] || ( echo "Can not locate file: $1" && exit 1 )

# check if file is within _WORK_DIR
if [[ "$file_to_add" =~ ^"$GG_BACKUP_ROOT".* ]]; then
	echo "Not backing up the backup in the backup :)"
	exit 1
fi

# --delete-after to remove files no longer present in source
rsync -avR "$file_to_add" "$_WORK_DIR"

# Store metadata for all files being backed up
printf "Backing up metadata ..."
if [ -f "$file_to_add" ]; then
    # Single file
    store_metadata "$file_to_add" "$metadata_file"

elif [ -d "$file_to_add" ]; then
    # Directory - store metadata for all files
	files_list=$(find "$file_to_add" -type f)
	for file in $files_list; do
		store_metadata "$file" "$metadata_file"
	done
fi
printf "Done.\n"

# Generate HTML overview
generate_html_overview "$_WORK_DIR" "$_LAYER_DIR" "$GG_LAYER"
