#!/usr/bin/env fish

# ggfiles init file for fish
# Source with: source /path/to/ggpath.fish

set SCRIPT_DIR (cd (dirname (status --current-filename)); and pwd)

if not string match -q "*_ggfiles*" $PATH
    set -gx PATH $PATH $SCRIPT_DIR
    echo $SCRIPT_DIR added to '$PATH'
end

set -gx GG_BACKUP_ROOT $SCRIPT_DIR/../ggrepo
