#!/usr/bin/env bash

# ggfiles init file for bash
# Source with: source /path/to/ggpath.bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [[ ! $PATH =~ "_ggfiles" ]]; then
    PATH=$PATH:$SCRIPT_DIR
    echo "$SCRIPT_DIR added to \$PATH"
fi

export GG_BACKUP_ROOT=$SCRIPT_DIR/../ggrepo
