#!/usr/bin/env bash

. $(which _ggperm_util)
. $(which _gg_check_root)
. $(which _gg_check_layer)

pwd_before_update=$(pwd)

cd "$_WORK_DIR" || exit 1

printf "Updating backup file list ...\n"
tmp_errors=$(mktemp)
relative_file_list "$_WORK_DIR" | rsync -av  --files-from=- / "$_WORK_DIR" 2>$tmp_errors
if [ $? -ne 0 ]; then
	printf "There were errors updating backup files:\n"
	cat $tmp_errors | egrep "rsync:"
	rm $tmp_errors
	exit 1
fi

#files_list=$(find . -type f)

#relative_file_list "$_WORK_DIR" | rsync -a --files-from=- / "$_WORK_DIR"

# Update backed-up files
# find . -type f | while read -r file; do
#     # Remove leading ./ from file path
#     rel_path="${file#./}"
#     src_file="/$rel_path"
#     dest_file="$_WORK_DIR/$rel_path"

#     if [ -e "$src_file" ]; then
#         echo "Updating backup of $src_file..."
#         rsync -a "$src_file" "$dest_file"
#     else
#         echo "Source file $src_file no longer exists. Consider removing from backup."
#     fi
# done

# Update permissions and ownership backed-up files and folders
printf "Updating backup permissions ..."
find . | while read -r file; do
	# Remove leading ./ from file path
	rel_path="${file#./}"
	src_file="/$rel_path"
	dest_file="$_WORK_DIR/$rel_path"

	if [ -e "$src_file" ]; then
        if [ -d "$src_file" ]; then
			_perm=$(get_file_perm "$src_file/")
			_ownr=$(get_file_own "$src_file/")
			chmod "$_perm" "$dest_file/"
			chown "$_ownr" "$dest_file/"
        else
			_perm=$(get_file_perm "$src_file")
			_ownr=$(get_file_own "$src_file")
			chmod "$_perm" "$dest_file"
			chown "$_ownr" "$dest_file"
        fi
    fi
	printf "."
done
printf "\n Done.\n "

cd "$pwd_before_update" || exit 1
